[package]
name = "ublox"
version = "0.1.0"
authors = ["Lane Kolbly <lane@rscheme.org>"]
edition = "2018"
license = "MIT"
description = "A crate to communicate with u-blox GPS devices using the UBX protocol"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serialport = "3.3.0"
bincode = "1.2.1"
chrono = "0.4"
crc = "1.8.1"
syn = "1.0.14"
ublox_derive = { path = "ublox_derive/" }
num-traits = "0.2"
num-derive = "0.2"
